version: "3.8"

services:
  alpine:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5555:80"
    volumes:
      - ./conf/site.conf:/etc/nginx/http.d/default.conf
      - ./src:/var/www/html
    networks:
      - acpSymfony

  db:
    image: mariadb:10.8.2
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
<<<<<<< HEAD
<<<<<<< HEAD
      MYSQL_ROOT_PASSWORD: "ChangeMeLater"
=======
      MYSQL_ROOT_PASSWORD: "password"
>>>>>>> develop
=======
      MYSQL_ROOT_PASSWORD: "password"
>>>>>>> refs/remotes/origin/log
    networks:
      - acpSymfony

volumes:
  db-data:

networks:
  acpSymfony:
